### ISSUE TITLE
Dorzucenie linku do https://carbon.now.sh/

### ISSUE THREAD

**Issue by psmyrdek** [warsawjs/good-speaker-guide#7]
https://carbon.now.sh/ to narzędzie dostępne online pozwalające nam zaprezentować fragmenty kodu źródłowego w przejrzysty i przyjazny dla publiczności sposób:

![carbon](https://user-images.githubusercontent.com/6187417/56153683-09d33000-5fb7-11e9-8872-0716de613b8e.png)

1) Czy nadaje się do dorzucenia do guide'a?
2) Jeśli tak, to [tutaj](https://github.com/warsawjs/good-speaker-guide/blob/master/chapters/slides-typography.md#prezentacja-kodu-%C5%BAr%C3%B3d%C5%82owego) czy bardziej [tutaj](https://github.com/warsawjs/good-speaker-guide/blob/master/chapters/slides-frameworks.md)?

**Comment by piecioshka** [comment]
@psmyrdek świetny pomysł! Dodam z chęcią do wskazówek dot. tworzenia slajdów :)

**Comment by piecioshka** [comment]
@psmyrdek dodałem usługę do sekcji "ryzykowne" 😄 

Bardzo rzadko kod na ciemnym tle dobrze wygląda. Trzeba mieć bardzo dobrą lampę lub telewizor zamiast projektora 👍

**Comment by psmyrdek** [comment]
Prawda, chociaż tutaj możesz zmieniać schemat kolorów tak jak w IDE: 

![image](https://user-images.githubusercontent.com/6187417/56304127-b808e200-613d-11e9-889a-3b5a0f71e51c.png)

Ja ostatnio miałem możliwośc zgaszenia światła w trakcie prelekcji i nawet ten ciemny motyw wyszedł dobrze. No ale fakt, warto to mieć na uwadze.

**Comment by psmyrdek** [comment]
Taki setup np. powinien zadziałać:
https://carbon.now.sh/?bg=rgba(242%2C242%2C242%2C1)&t=one-light&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=4x&wm=false
