### ISSUE TITLE
Release only

### ISSUE THREAD

**Issue by TomaszWaszczyk** [warsawjs/good-speaker-guide#8]
Róbcie releasy tego repo, ciekawe!

**Comment by piecioshka** [comment]
@TomaszWaszczyk A wg Ciebie powinno kryć się pod releasem w tym repo?

**Comment by TomaszWaszczyk** [comment]
Zrobienie wydania raz jakiś czas na repozytorium w Github (w ten sposób wiele repo obserwuję - bez szumu).

**Comment by piecioshka** [comment]
Of course! Zaraz będzie pierwszy release! :)

**Comment by piecioshka** [comment]
@TomaszWaszczyk zrobiona pierwsza wersja — #52b11d8 🎉

**Comment by TomaszWaszczyk** [comment]
Raz na kwartał, albo raz na pół roku będzie super. Dziękuję! Dodam coś od siebie w wolnej chwilii.
